export const ADD_HOTEL_START = "ADD_HOTEL_START";
export const ADD_HOTEL_SUCCESS = "ADD_HOTEL_SUCCESS";
export const ADD_HOTEL_FAIL = "ADD_HOTEL_FAIL";

export const HOTEL_REDIRECT_PATH = "HOTEL_REDIRECT_PATH";

export const EDIT_HOTEL_START = "EDIT_HOTEL_START";
export const EDIT_HOTEL_SUCCESS = "EDIT_HOTEL_SUCCESS";
export const EDIT_HOTEL_FAIL = "EDIT_HOTEL_FAIL";

export const DELETE_HOTEL_START = "DELETE_HOTEL_START";
export const DELETE_HOTEL_SUCCESS = "DELETE_HOTEL_SUCCESS";
export const CANCEL_HOTEL_DELETE = "CANCEL_HOTEL_DELETE";
export const DELETE_HOTEL_FAIL = "DELETE_HOTEL_FAIL";

export const ENABLE_HOTEL_START = "ENABLE_HOTEL_START";
export const ENABLE_HOTEL_SUCCESS = "ENABLE_HOTEL_SUCCESS";
export const ENABLE_HOTEL_FAIL = "ENABLE_HOTEL_FAIL";

export const FEATURE_HOTEL_START = "FEATURE_HOTEL_START";
export const FEATURE_HOTEL_SUCCESS = "FEATURE_HOTEL_SUCCESS";
export const FEATURE_HOTEL_FAIL = "FEATURE_HOTEL_FAIL";

export const GET_HOTELS_START = "GET_HOTELS_START";
export const GET_HOTELS_SUCCESS = "GET_HOTELS_SUCCESS";
export const GET_HOTELS_FAIL = "GET_HOTELS_FAIL";

export const GET_HOTEL_START = "GET_HOTEL_START";
export const GET_HOTEL_SUCCESS = "GET_HOTEL_SUCCESS";
export const GET_HOTEL_FAIL = "GET_HOTEL_FAIL";

export const GET_HOTEL_TYPES_SUCCESS = "GET_HOTEL_TYPES_SUCCESS";
export const GET_HOTEL_TYPES_FAIL = "GET_HOTEL_TYPES_FAIL";
